cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

catalogue/urls.py
from django.urls import path

from . import views

app_name = 'catalogue'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>', views.product_list, name='product_list_by_category'),
    path('<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
]

ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('catalogue.urls', namespace='catalogue')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

catalogue/models.py
from django.db import models
from django.urls import reverse
from django.db.models.deletion import CASCADE


class Category(models.Model):
    """ Category Model """
    name = models.CharField(
        max_length=100,
        unique=True
    )

    slug = models.SlugField(
        max_length=100,
        unique=True
    )

    class Meta:
        ordering = ('-name',)
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse(
            'catalogue:product_list_by_category',
            args=[self.slug]
        )
    
    def __str__(self):
        return self.name
    

class Product(models.Model):
    """ Product Details Model """
    category = models.ForeignKey(
        Category,
        related_name = 'products',
        on_delete = models.CASCADE
    )

    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    image = models.ImageField(upload_to='products/')
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ('-name',)
    
    def get_absolute_url(self):
        return reverse(
            'catalogue:product_detail',
            args=[self.category.slug, self.slug]
        )

catalogue/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product
from cart.forms import CartAddProductForm

def product_list(request, category_slug=None):
    """ Fetches products pased on selected category """
    categories = Category.objects.all()
    requested_category = None
    products = Product.objects.all()

    # Filter products by category
    if category_slug:
        requested_category = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=requested_category)

    return render(
        request,
        'product/list.html',
        {
            'categories': categories,
            'requested_category': requested_category,
            'products': products
        }
    )

def product_detail(request, category_slug, product_slug):
    """ Handles product details page """
    category = get_object_or_404(Category, slug=category_slug)
    product = get_object_or_404(
        Product,
        category_id=category.id,
        slug=product_slug
    )
    cart_product_form = CartAddProductForm()
    return render(
        request,
        'product/detail.html',
        {
            'product': product,
            'cart_product_form': cart_product_form,
        }
    )

catalogue/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <!-- FontAwesome -->
    <script src="https://kit.fontawesome.com/b2e6bb265b.js" crossorigin="anonymous"></script>
    <!-- Local CSS Styles -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <!-- Navbar -->
    <nav
      class="navbar navbar-expand-md navbar-dark blur-cards fixed-top py-1"
      id="main-nav"
    >
      <div class="container">
        <!-- Branding -->
        <a href="{% url 'catalogue:product_list' %}" class="navbar-brand">
          <h3 class="font-weight-bold">MenStore</h3>
        </a>

        <!-- Burger Menu -->
        <button class="navbar-toggler" data-toggle="collapse" 
          data-target="#navbarCollapse">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Menu Items -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
          <ul class="navbar-nav ml-auto ">
            {% if request.user.is_authenticated %}
              <!-- Profile -->
              <li class="nav-item mx-2">
                <a href="{% url 'profile' %}" class="nav-link text-white">
                  <i class="fas fa-user"></i> {{ request.user.first_name }}
                </a>
              </li>
              <!-- Logout -->
              <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link text-white">
                  <i class="fas fa-sign-out-alt"></i> Log out
                </a>
              </li>
              {% else %}
              <!-- Login -->
              <li class="nav-item">
                <a href="{% url 'login' %}" class="nav-link text-white">
                  <i class="fas fa-sign-in-alt"></i> Log in
                </a>
              </li>
              <!-- Register -->
              <li class="nav-item">
                <a href="{% url 'register' %}" class="nav-link text-white">
                  <i class="fas fa-user-plus"></i> Register
                </a>
              </li>
            {% endif %}

            <!-- Cart -->
            <li class="nav-item">
              <div class="dropdown-custom">
                <a href="{% url 'cart:cart_detail' %}" 
                  class="nav-link text-white drop-btn">
                  <i class="fas fa-shopping-cart"></i>
                  ₹<span id="cart_price">{{ cart_total_price|floatformat:2 }}</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Main Page Content -->
    <div class="container py-5" style="min-height: 800px;">
      {% block content %} {% endblock content %}
    </div>

    <!-- Footer -->
    <footer style="bottom: 0%;">
      <div class="py-3 blur-black">
        <div class="text-center">
          Copyright © 2022, All Rights Reserved
        </div>
      </div>
    </footer>

    <!-- Bootstrap Scripts -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  </body>
</html>